language: python
python:
  - 2.7
  - 3.5
  - 3.6

os:
  - linux
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
env:
  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - PYTHON=2.7
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - PYTHON=3.5
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - PYTHON=3.6
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - PYTHON=3.7

before_install:
  - sudo chmod +x .travis/install.sh && sudo chown $USER .travis/install.sh && /bin/bash .travis/install.sh

install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      export MGRA_PATH="/Users/travis/build/aganezov/gos-asm/mgra/build/src/mgra/indel_mgra";
    else
      export MGRA_PATH="/home/travis/build/aganezov/gos-asm/mgra/build/src/mgra/indel_mgra";
    fi
  - echo $MGRA_PATH
  - python setup.py develop

script:
  - echo $MGRA_PATH
  - gos-asm.py gos_asm/examples/w_repeats/chimp/2000/config.py